apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq3-0
  namespace: default
spec:
  containers:
  - name: rabbitmq3
    image: bitnami/rabbitmq:latest
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "256Mi"