apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq3-0
  namespace: default
  labels:
    app: rabbitmq3
spec:
  containers:
    - name: rabbitmq3
      image: rabbitmq:management
      resources:
        limits:
          memory: "1Gi"
        requests:
          memory: "512Mi"        
      ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: http
      env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: storage-collector-dev
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest