apiVersion: v1
kind: Service
metadata:
  name: simple-api-loop-service
  namespace: test
spec:
  selector:
    app: simple-api-loop
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
