apiVersion: v1
kind: Service
metadata:
  name: simple-api-loop-service
  namespace: test
  labels:
    app: simple-api-loop
spec:
  selector:
    app: simple-api-loop
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
