apiVersion: v1
kind: Service
metadata:
  name: simple-api-loop-service
  labels:
    app: simple-api-loop  
spec:
  selector:
    app: simple-api-loop  
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 39090
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: ClusterIP
